# -*- coding: utf-8 -*-
"""Toxic_Comment_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12AcupCX9HPbasGU1iAIpSTrc0lzX12Ps

BOCHARD-DUMAS-LABRACHERIE-LAVAUX PROJECT
"""

# Only 1 time if never ran before !
!pip install -U "transformers>=4.40" "datasets>=2.18" "accelerate>=0.33" evaluate

import sys
! "{sys.executable}" -m pip install --upgrade pip
! "{sys.executable}" -m pip install --no-cache-dir transformers datasets accelerate pandas numpy scikit-learn tqdm matplotlib sentence-transformers
! "{sys.executable}" -m pip install torch torchvision torchaudio
# ou avec CUDA 12.1 :
# ! "{sys.executable}" -m pip install --index-url https://download.pytorch.org/whl/cu121 torch torchvision torchaudio

# Standard library
import hashlib
import random
import re
import time
import unicodedata
import warnings
from time import perf_counter

# Numerical / Data
import numpy as np
import pandas as pd

# Visualization
import matplotlib.pyplot as plt

# NLP (NLTK)
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

# Machine Learning (scikit-learn)
from sklearn.feature_extraction.text import (
    CountVectorizer,
    HashingVectorizer,
    TfidfTransformer,
    TfidfVectorizer,
)
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    auc,
    average_precision_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_recall_curve,
    precision_recall_fscore_support,
    roc_auc_score,
    roc_curve,
)
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC
from sklearn.utils.class_weight import compute_class_weight

# Deep Learning (PyTorch)
import torch
import torch.nn as nn
from torch import amp
from torch.utils.data import DataLoader, Dataset

# Transformers (Hugging Face)
from transformers import (
    DataCollatorWithPadding,
    DistilBertForSequenceClassification,
    DistilBertTokenizerFast,
    get_linear_schedule_with_warmup,
)

# Sentence Embeddings
from sentence_transformers import SentenceTransformer

# Load dataset

data_comments = pd.read_csv("train.csv")

# Keep only the three relevant columns (id, text, label)
data_comments = data_comments[["id", "comment_text", "toxic"]]

# Display a quick preview of the data
print(data_comments.head())
print(data_comments.columns)

# Class distribution
print("\nClass distribution:")
print(data_comments["toxic"].value_counts())

N = 10
ex = data_comments.loc[data_comments["toxic"] == 1, ["id", "comment_text"]].sample(n=N, random_state=0)

for i, row in ex.reset_index(drop=True).iterrows():
    txt = str(row["comment_text"]).replace("\n", " ")
    print(f"{i+1:02d}. [id={row['id']}] {txt[:200]}")

"""## Code from Project 1 ##"""

# Stopwords: keep negations and second person (they carry sentiment/polarity)
KEEP = {"not", "no", "nor", "n't", "never", "you", "your", "ur", "u", "youre"}
STOP = set(stopwords.words('english'))
STOP -= KEEP

# Deobfuscation mapping
# NOTE: We do NOT map '!' globally (to avoid "!!!" -> "iii").
#       We only map '!' to 'i' when it appears BETWEEN letters (e.g., b!tch -> bitch).
DEOB = str.maketrans({
    '@': 'a', '4': 'a',
    '1': 'i', '|': 'i',
    '3': 'e',
    '0': 'o',
    '$': 's', '5': 's',
    '7': 't',
    '€': 'e', '£': 'l'
})

EMAIL_RE   = re.compile(r'(?i)\b[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}\b')
MENTION_RE = re.compile(r'(?<!\S)@\w+')

def normalize_repeats(token: str, max_repeat: int = 3) -> str:
    """Compress runs of the same char to at most `max_repeat` (e.g., sooooo -> sooo)."""
    return re.sub(r'(.)\1{' + str(max_repeat) + r',}', lambda m: m.group(1) * max_repeat, token)

def preprocess_text(text: str) -> str:
    """Toxicity preprocessing (EN) — keeps '!!' and '??', no forced ALLCAPS demotion."""
    if not isinstance(text, str):
        text = str(text)

    # 1) Unicode normalization
    t = unicodedata.normalize('NFKC', text)

    # 2) Remove URLs
    t = re.sub(r'https?://\S+|www\.\S+', ' ', t)

    # 3) Remove emails
    t = EMAIL_RE.sub(' ', t)

    # 4) Remove @mentions
    t = MENTION_RE.sub(' ', t)

    # 4-bis) PROTECT punctuation runs (before further cleaning)
    t = re.sub(r'!{2,}', ' __EXCL__ ', t)
    t = re.sub(r'\?{2,}', ' __QUEST__ ', t)

    # 5) Deobfuscation (e.g., '@'->'a', '1'->'i', etc.)
    t = t.translate(DEOB)

    # 5-bis) Map '!' to 'i' only when between letters (b!tch -> bitch)
    t = re.sub(r'(?i)(?<=[a-z])!(?=[a-z])', 'i', t)

    # 6) Punctuation cleanup to avoid glued tokens
    #    - remove solitary '!' or '?' (runs are preserved via placeholders)
    t = re.sub(r'(?<![!?])[!?](?![!?])', ' ', t)
    #    - replace .,;: with spaces
    t = re.sub(r'[.,;:]+', ' ', t)

    # 7) Tokenization
    toks = word_tokenize(t)

    out = []
    for tok in toks:
        raw_tok = tok  # keep original case

        # A) Restore protected runs
        if raw_tok == "__EXCL__":
            out.append("!!");  continue
        if raw_tok == "__QUEST__":
            out.append("??");  continue

        # B) Token cleanup (allow A–Z to preserve true ALLCAPS)
        tok = re.sub(r"<.*?>", " ", raw_tok)
        tok = re.sub(r"&[a-z]+;", " ", tok)
        tok = re.sub(r"[^A-Za-z']+", "", tok)
        tok = tok.replace("'", "")

        if not tok or '@' in tok:
            continue

        # C) Normalize character repeats (FUUUUCK -> FUUU, sooooo -> sooo)
        tok = normalize_repeats(tok, max_repeat=3)
        if not tok:
            continue

        # D) Stopwords (case-insensitive), with whitelist preserved above
        if tok.lower() in STOP:
            continue

        # E) Output: keep real ALLCAPS (len>1), else lowercase
        out.append(tok if (tok.isupper() and len(tok) > 1) else tok.lower())

    return " ".join(out)

# Apply preprocessing
data_comments["processed_text"] = data_comments["comment_text"].astype(str).apply(preprocess_text)

# Quick checks
print("Preprocessing preview:")
print(data_comments[["comment_text", "processed_text"]].head(8))

print("\nClass balance (normalized):")
print(
    data_comments["toxic"]
    .value_counts(normalize=True)
    .rename({0: "non-toxic", 1: "toxic"})
)

## BoW

# Token pattern:
# - alphabetic words: [A-Za-z]+
# - emphasis punctuation runs: [!?]{2,} (keeps "!!", "??", "!!!", ...)
TOKEN_PATTERN = r"(?u)(?:[A-Za-z]+|[!?]{2,})"

# N-gram configurations to compare
ngram_ranges = {
    "Unigram (1,1)": (1, 1),
    "Bigram  (1,2)": (1, 2),
    "Trigram (1,3)": (1, 3),
}

print("=== BoW over the FULL corpus (exploration) ===")
for name, ngram in ngram_ranges.items():
    vec = CountVectorizer(
        ngram_range=ngram,
        lowercase=False,
        token_pattern=TOKEN_PATTERN
    )
    X_bow = vec.fit_transform(data_comments["processed_text"])
    n_docs, n_feats = X_bow.shape
    nnz = X_bow.count_nonzero()
    sparsity = 1.0 - (nnz / (n_docs * n_feats))

    print(
        f"{name}: shape={X_bow.shape} | "
        f"vocab={n_feats:,} | nnz={nnz:,} | sparsity={sparsity*100:.2f}%"
    )

    # Split (stratifié) sur le texte prétraité
X_text = data_comments["processed_text"].astype(str)
y = data_comments["toxic"].astype(int)

X_train_text, X_test_text, y_train, y_test = train_test_split(
    X_text, y, test_size=0.20, random_state=42, stratify=y
)

## Vectoriseur TF-IDF (config #6 du projet 1)
tfidf = TfidfVectorizer(
    max_features=2_000_000,
    ngram_range=(1, 2),
    min_df=1,
    max_df=0.85,
    lowercase=False,     # cohérence avec pré traitement
    sublinear_tf=True,
    dtype=np.float32
)

X_train = tfidf.fit_transform(X_train_text)
X_test  = tfidf.transform(X_test_text)

## Modèle LinearSVC (baseline P2)
model_svc = LinearSVC(
    random_state=42,
    max_iter=4000,
    class_weight="balanced"
)
model_svc.fit(X_train, y_train)

# Prédictions + métriques
y_pred_test_svc = model_svc.predict(X_test)
y_scores_svc = model_svc.decision_function(X_test)  # scores continus

print("\nLinearSVC (TF-IDF 1–2g) — TEST")
print(classification_report(y_test, y_pred_test_svc, digits=3))
print("ROC-AUC:", round(roc_auc_score(y_test, y_scores_svc), 4),
      "| PR-AUC (toxic):", round(average_precision_score(y_test, y_scores_svc), 4))

"""## Part 1 - Baseline"""

# Baseline creation

TOKEN_PATTERN = r"(?u)(?:[A-Za-z]+|[!?]{2,})"  # pour garder '!!', '??'

pipe_svm = Pipeline([
    ("tfidf", TfidfVectorizer(
        ngram_range=(1, 2),
        max_df=0.85,
        min_df=1,
        max_features=2_000_000,
        lowercase=False,        # pour rester cohérent avec notre preprocessing
        sublinear_tf=True,      # cohérence avec best config
        dtype=np.float32,
        token_pattern=TOKEN_PATTERN  # pour garder '!!'/'??'
    )),
    ("clf", LinearSVC(
        class_weight="balanced",
        random_state=42,
        max_iter=4000
    ))
])

t0 = perf_counter(); pipe_svm.fit(X_train_text, y_train); t1 = perf_counter()

y_pred  = pipe_svm.predict(X_test_text)
X_test_tfidf = pipe_svm.named_steps["tfidf"].transform(X_test_text)
y_score = pipe_svm.named_steps["clf"].decision_function(X_test_tfidf)

print(classification_report(y_test, y_pred, digits=3))
print("ROC-AUC:", round(roc_auc_score(y_test, y_score), 4),
      "| PR-AUC (toxic):", round(average_precision_score(y_test, y_score), 4),
      "| Train+Infer time (s):", round(t1 - t0, 1))

"""## Part 2 - Word embeddings"""

## MiniLM sentence embeddings + simple classifiers (with threshold policies)

# 0) Light cleaning (right for embeddings/transformers)
EMAIL_RE   = re.compile(r'(?i)\b[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}\b')
MENTION_RE = re.compile(r'(?<!\S)@\w+')
DEOB = str.maketrans({'@':'a','4':'a','1':'i','|':'i','3':'e','0':'o','$':'s','5':'s','7':'t','€':'e','£':'l'})

def light_clean(s: str) -> str:
    s = unicodedata.normalize('NFKC', str(s))
    s = re.sub(r'https?://\S+|www\.\S+', ' ', s)
    s = EMAIL_RE.sub(' ', s)
    s = MENTION_RE.sub(' ', s)
    s = s.translate(DEOB)   # mild deobfuscation only
    return s.strip()

# 1) Data
df = data_comments.dropna(subset=["comment_text","toxic"]).copy()
df["clean"] = df["comment_text"].astype(str).map(light_clean)
X_text = df["clean"].tolist()
y = df["toxic"].astype(int).values

X_train_text, X_test_text, y_train, y_test = train_test_split(
    X_text, y, test_size=0.20, random_state=42, stratify=y
)

# 2) Encode with MiniLM
from sentence_transformers import SentenceTransformer
se_model = SentenceTransformer("all-MiniLM-L6-v2")

t0 = perf_counter()
X_train_emb = se_model.encode(X_train_text, batch_size=256, show_progress_bar=True, normalize_embeddings=True)
X_test_emb  = se_model.encode(X_test_text,  batch_size=256, show_progress_bar=True,  normalize_embeddings=True)
encode_time = perf_counter() - t0

print(f"Embeddings → train {X_train_emb.shape}, test {X_test_emb.shape} | Encode time (s): {encode_time:.1f}")

# 3) Classifier A: Logistic Regression (probabilities → threshold tuning)
t1 = perf_counter()
clf_lr = LogisticRegression(max_iter=2000, class_weight="balanced", n_jobs=-1)
clf_lr.fit(X_train_emb, y_train)
train_time_lr = perf_counter() - t1

y_pred_lr  = clf_lr.predict(X_test_emb)
y_proba_lr = clf_lr.predict_proba(X_test_emb)[:, 1]

print("\n=== MiniLM + LR (default threshold 0.5) ===")
print(classification_report(y_test, y_pred_lr, target_names=["non-toxic","toxic"], digits=3))
print("ROC-AUC:", round(roc_auc_score(y_test, y_proba_lr), 4),
      "| PR-AUC (toxic):", round(average_precision_score(y_test, y_proba_lr), 4),
      f"| Train time (s): {train_time_lr:.1f} | Encode time (s): {encode_time:.1f}")

# Threshold policies
prec, rec, thr = precision_recall_curve(y_test, y_proba_lr)
f1 = (2*prec*rec)/(prec+rec+1e-12)
thr_balanced  = thr[np.nanargmax(f1[1:])]  # max F1 on this split (illustrative)
thr_prec85    = thr[np.where(prec[1:] >= 0.85)[0][0]] if np.any(prec[1:] >= 0.85) else 0.5

def eval_at_threshold(t, tag):
    y_hat = (y_proba_lr >= t).astype(int)
    print(f"\n-- LR threshold {tag} @ {t:.3f} --")
    print(classification_report(y_test, y_hat, target_names=["non-toxic","toxic"], digits=3))

eval_at_threshold(thr_balanced, "balanced")
eval_at_threshold(thr_prec85,   "precision85")
eval_at_threshold(0.5,          "0.5 (reference)")

# 4) Classifier B: Linear SVM (strong baseline on embeddings)
t2 = perf_counter()
svm_se = LinearSVC(class_weight="balanced", random_state=42)
svm_se.fit(X_train_emb, y_train)
train_time_svm = perf_counter() - t2

y_pred_svm  = svm_se.predict(X_test_emb)
scores_svm  = svm_se.decision_function(X_test_emb)

print("\n=== MiniLM + LinearSVC ===")
print(classification_report(y_test, y_pred_svm, target_names=["non-toxic","toxic"], digits=3))
print("ROC-AUC:", round(roc_auc_score(y_test, scores_svm), 4),
      "| PR-AUC (toxic):", round(average_precision_score(y_test, scores_svm), 4),
      f"| Train time (s): {train_time_svm:.1f} | Encode time (s): {encode_time:.1f}")

# 5) Small summary table
def summarize(name, y_true, y_pred, scores, train_s, encode_s):
    p, r, f1_each, _ = precision_recall_fscore_support(y_true, y_pred, average=None, labels=[0,1])
    macro_f1 = f1_score(y_true, y_pred, average="macro")
    return {
        "Model": name,
        "Toxic P": round(p[1], 3), "Toxic R": round(r[1], 3), "Toxic F1": round(f1_each[1], 3),
        "Macro-F1": round(macro_f1, 3),
        "ROC-AUC": round(roc_auc_score(y_true, scores), 4),
        "PR-AUC (toxic)": round(average_precision_score(y_true, scores), 4),
        "Train (s)": round(train_s, 1),
        "Encode (s)": round(encode_s, 1),
    }

summary_rows = [
    summarize("MiniLM + LR (0.5)",  y_test, y_pred_lr,  y_proba_lr,  train_time_lr,  encode_time),
    summarize("MiniLM + SVM",       y_test, y_pred_svm, scores_svm,  train_time_svm, encode_time),
]
display(pd.DataFrame(summary_rows))

"""## Partie 3 - Transformers"""

import os, random, numpy as np, pandas as pd, torch, torch.nn as nn
from time import perf_counter
from datasets import Dataset
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, roc_auc_score, average_precision_score, accuracy_score
from sklearn.utils.class_weight import compute_class_weight
from transformers import (AutoTokenizer, AutoModelForSequenceClassification,
                          Trainer, TrainingArguments, DataCollatorWithPadding)

# Couper Weights & Biases
os.environ["WANDB_DISABLED"] = "true"
os.environ["WANDB_MODE"] = "disabled"

# Reproductibilité
SEED = 42
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED); torch.cuda.manual_seed_all(SEED)
os.environ["PYTHONHASHSEED"] = str(SEED)

# 1) Données
df = data_comments.dropna(subset=["comment_text","toxic"]).copy()
df["text"] = df["comment_text"].astype(str)
df["label"] = df["toxic"].astype(int)

X_train, X_test, y_train, y_test = train_test_split(
    df["text"], df["label"], test_size=0.2, random_state=SEED, stratify=df["label"]
)
train_df = pd.DataFrame({"text": X_train.values, "label": y_train.values})
test_df  = pd.DataFrame({"text": X_test.values,  "label": y_test.values})

ds_train = Dataset.from_pandas(train_df, preserve_index=False)
ds_test  = Dataset.from_pandas(test_df,  preserve_index=False)

# 2) Modèle & tokenizer
model_id = "roberta-base"     # plus puissant que distilBERT → meilleur potentiel
max_len  = 128                # séquences plus courtes → entraînement plus rapide
tok = AutoTokenizer.from_pretrained(model_id, use_fast=True)

def tokenize(batch):
    return tok(batch["text"], truncation=True, padding=False, max_length=max_len)

ds_train_tok = ds_train.map(tokenize, batched=True, remove_columns=["text"])
ds_test_tok  = ds_test.map(tokenize,  batched=True, remove_columns=["text"])
collator = DataCollatorWithPadding(tokenizer=tok)

model = AutoModelForSequenceClassification.from_pretrained(model_id, num_labels=2)

# Poids de classe (déséquilibre)
classes = np.array([0, 1])
cls_w = compute_class_weight(class_weight="balanced", classes=classes, y=y_train)
class_weights = torch.tensor(cls_w, dtype=torch.float32)

# Trainer patché : perte pondérée + label smoothing
class WeightedTrainer(Trainer):
    def __init__(self, *args, class_weights=None, label_smoothing=0.0, **kwargs):
        super().__init__(*args, **kwargs)
        self.class_weights = class_weights
        self.label_smoothing = float(label_smoothing)

    # Accepte les kwargs potentiels (ex: num_items_in_batch)
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits

        if self.label_smoothing > 0:
            num_labels = logits.size(-1)
            with torch.no_grad():
                true_dist = torch.zeros_like(logits)
                true_dist.fill_(self.label_smoothing / (num_labels - 1))
                true_dist.scatter_(1, labels.unsqueeze(1), 1.0 - self.label_smoothing)
            log_probs = torch.log_softmax(logits, dim=-1)
            weights = self.class_weights.to(logits.device)
            per_ex_weight = weights[labels]
            loss = -(per_ex_weight * (true_dist * log_probs).sum(dim=1)).mean()
        else:
            loss_fct = nn.CrossEntropyLoss(weight=self.class_weights.to(logits.device))
            loss = loss_fct(logits, labels)

        return (loss, outputs) if return_outputs else loss

# TrainingArguments : moderne -> fallback legacy
def make_args_compat(num_epochs=2, lr=2e-5):
    common = dict(
        output_dir="out_roberta_weighted",
        learning_rate=lr,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=64,
        num_train_epochs=num_epochs,
        weight_decay=0.01,
        logging_steps=100,
        seed=SEED,
    )
    try:
        args = TrainingArguments(
            **common,
            fp16=torch.cuda.is_available(),
            report_to="none",
            evaluation_strategy="no",   # on évalue APRÈS l'entraînement
            save_strategy="no",
            warmup_ratio=0.06,
            gradient_accumulation_steps=1,
        )
        return args, True
    except TypeError:
        # Fallback legacy (pas de clés modernes)
        args = TrainingArguments(**common)
        return args, False

args, modern_ok = make_args_compat(num_epochs=2, lr=2e-5)
trainer = WeightedTrainer(
    model=model,
    args=args,
    train_dataset=ds_train_tok,
    eval_dataset=ds_test_tok,     # on s’en sert pour predict() après
    tokenizer=tok,
    data_collator=collator,
    class_weights=class_weights,
    label_smoothing=0.05,         # petit lissage → gains de stabilité
)

# Entraînement
t0 = perf_counter()
trainer.train()
train_time = perf_counter() - t0

# Évaluation détaillée (TEST)
pred = trainer.predict(ds_test_tok)
logits = pred.predictions
labels = pred.label_ids
probs  = torch.softmax(torch.tensor(logits), dim=1).numpy()[:, 1]
y_hat  = logits.argmax(axis=1)

print("\n=== RoBERTa-base (weighted + smoothing) — TEST ===")
print(classification_report(labels, y_hat, target_names=["non-toxic","toxic"], digits=3))
roc = roc_auc_score(labels, probs)
pr  = average_precision_score(labels, probs)
print(f"ROC-AUC: {roc:.4f} | PR-AUC (toxic): {pr:.4f}")
print(f"Train time (s): {train_time:.1f}")

# Inférence (coût)
from transformers import TextClassificationPipeline
pipe = TextClassificationPipeline(model=trainer.model, tokenizer=tok, device=0 if torch.cuda.is_available() else -1)
samples = [
    "You are a disgusting idiot!!",
    "I disagree with you, but let's stay respectful.",
    "She is a woman."
]
t1 = perf_counter()
out = pipe(samples); infer_time = perf_counter() - t1
print("\nInference samples:")
for s, o in zip(samples, out):
    print(f"- {s} -> {o}")
print(f"Inference time for {len(samples)} samples (s): {infer_time:.3f}")

from sklearn.metrics import confusion_matrix
import joblib, json

cm = confusion_matrix(labels, (probs>=0.5).astype(int), labels=[0,1])
print("Confusion matrix:\n", cm)

# Sauvegarde du modèle/tokenizer et métriques
trainer.save_model("roberta_toxic_ckpt")
tok.save_pretrained("roberta_toxic_ckpt")
with open("metrics_test.json","w") as f:
    json.dump({"roc_auc": float(roc), "pr_auc_toxic": float(pr)}, f, indent=2)
joblib.dump(cm, "confusion_matrix.joblib")

"""# Part 4"""

import pandas as pd
from sklearn.model_selection import train_test_split
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer,
)

# Données
CSV_PATH = "train.csv"

df = pd.read_csv(CSV_PATH)[["id", "comment_text", "toxic"]]
df["comment_text"] = df["comment_text"].astype(str)
df["toxic"] = df["toxic"].astype(int)

# Split STRATIFIÉ (préserve la proportion de classes entre train et test)
train_df, test_df = train_test_split(
    df,
    test_size=0.4,
    random_state=42,
    stratify=df["toxic"]
)

# Conversion en DatasetDict
datasets = DatasetDict({
    "train": Dataset.from_pandas(train_df, preserve_index=False),
    "test":  Dataset.from_pandas(test_df,  preserve_index=False),
})

# Modèle / tokenizer
model_name = "google/flan-t5-small"
tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model)

# Prétraitement minimal
prefix = "Classify the Wikipedia comment as toxic or non-toxic: "
MAX_INPUT_LEN = 128
MAX_TARGET_LEN = 4  # "toxic" / "not toxic"

def label_to_text(v: int) -> str:
    return "toxic" if int(v) == 1 else "not toxic"

def preprocess_function(examples):
    inputs = [prefix + x for x in examples["comment_text"]]
    targets = [label_to_text(v) for v in examples["toxic"]]

    model_inputs = tokenizer(
        inputs,
        max_length=MAX_INPUT_LEN,
        truncation=True,
    )
    # tokenisation des labels (obligatoire pour seq2seq)
    try:
        labels = tokenizer(text_target=targets, max_length=MAX_TARGET_LEN, truncation=True)
    except TypeError:
        # compat pour anciennes versions transformers
        with tokenizer.as_target_tokenizer():
            labels = tokenizer(targets, max_length=MAX_TARGET_LEN, truncation=True)

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

tokenized = datasets.map(
    preprocess_function,
    batched=True,
    remove_columns=datasets["train"].column_names,  # on enlève id/comment_text/toxic
)

# Entraînement
training_args = Seq2SeqTrainingArguments(
    output_dir="./results",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=4,
    num_train_epochs=2, #trop long sinon
    learning_rate=3e-4,
    weight_decay=0.01,
    save_total_limit=3,
    predict_with_generate=True,
    logging_steps=100,
    load_best_model_at_end=False,
)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized["train"],
    eval_dataset=tokenized["test"],
    tokenizer=tokenizer,
    data_collator=data_collator,
)

trainer.train()

trainer.save_model("./results/final")
tokenizer.save_pretrained("./results/final")

pip install pathlib

from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
from pathlib import Path

best_dir = Path("results/best").resolve()
tokenizer = AutoTokenizer.from_pretrained(best_dir, local_files_only=True, use_fast=True)
model = AutoModelForSeq2SeqLM.from_pretrained(best_dir, local_files_only=True)

import pandas as pd
import torch
import re
import unicodedata
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    BitsAndBytesConfig,
    pipeline,
)
from tqdm.auto import tqdm

#on utilise le modele fine tuned pour refaire comme à la premiere cellule
#
# Nettoyage léger
EMAIL_RE   = re.compile(r'(?i)\b[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}\b')
MENTION_RE = re.compile(r'(?<!\S)@\w+')
DEOB = str.maketrans({'@':'a','4':'a','1':'i','|':'i','3':'e','0':'o','$':'s','5':'s','7':'t','€':'e','£':'l'})

def light_clean(s: str) -> str:
    s = unicodedata.normalize('NFKC', str(s))
    s = re.sub(r'https?://\S+|www\.\S+', ' ', s)
    s = EMAIL_RE.sub(' ', s)
    s = MENTION_RE.sub(' ', s)
    s = s.translate(DEOB)
    return s.strip()

# Données
df = pd.read_csv("train.csv", usecols=["id", "comment_text", "toxic"])
df["clean_comment"] = df["comment_text"].astype(str).map(light_clean)
df["true_label_text"] = df["toxic"].map({0: "non-toxic", 1: "toxic"})

#30% des données trop long sinon
# df = df.sample(frac=0.001, random_state=42).reset_index(drop=True)

texts = df["clean_comment"].tolist()
y_true = (df["true_label_text"] == "toxic").astype(int).values

# Charger le modèle fine tuné
best_dir = "./results/best"  # répertoire où on a le bon modèle

quant_config = None
load_kwargs = {}

tokenizer = AutoTokenizer.from_pretrained(best_dir, use_fast=True)
model = AutoModelForSeq2SeqLM.from_pretrained(best_dir, **load_kwargs)

device = 0 if torch.cuda.is_available() else -1

pipe = pipeline(
    "text2text-generation",
    model=model,
    tokenizer=tokenizer,
    device=device,
    batch_size=32,
)

# Prompts (3 variantes)
PREFIX_TRAIN = "Classify the Wikipedia comment as toxic or non-toxic: "

ZS_PROMPT = (
    "Classify the Wikipedia comment as toxic or non-toxic. "
    "Answer with exactly one word: toxic or non-toxic.\nComment: "
)

FEW_SHOT_PREFIX = (
    "Classify each Wikipedia comment as toxic or non-toxic. "
    "Answer with exactly one word: toxic or non-toxic.\n"
    'Example: Comment: "You are an idiot." → toxic\n'
    'Example: Comment: "I think this article could use more sources." → non-toxic\n'
    'Example: Comment: "Stop being such a loser." → toxic\n'
)

ROLE_PREFIX = (
    "You are a moderation assistant. Respond with exactly one word: toxic or non-toxic.\nComment: "
)

MAX_NEW_TOKENS = 4

def normalize_pred(text: str) -> str:
    t = (text or "").strip().lower()
    if "toxic" in t and "not" not in t and "non" not in t:
        return "toxic"
    return "non-toxic"

def batched_generate(prompts, desc="Inference"):
    preds = []
    for i in tqdm(range(0, len(prompts), 32), desc=desc, unit="batch"):
        batch = prompts[i:i+32]
        outs = pipe(
            batch,
            max_new_tokens=MAX_NEW_TOKENS,
            clean_up_tokenization_spaces=True,
            num_beams=1,
            do_sample=False,
        )
        preds.extend([normalize_pred(o["generated_text"]) for o in outs])
    return preds

def predict_zero_shot(texts):
    prompts = [f"{ZS_PROMPT}{t[:400]}" for t in texts]
    return batched_generate(prompts, desc="Zero-Shot")

def predict_few_shot(texts):
    prompts = [f'{FEW_SHOT_PREFIX}Comment: "{t[:400]}" → ?' for t in texts]
    return batched_generate(prompts, desc="Few-Shot")

def predict_role_prompting(texts):
    prompts = [f"{ROLE_PREFIX}{t[:400]}" for t in texts]
    return batched_generate(prompts, desc="Role Prompting")

# Évaluer
def compute_metrics(y_true_bin, y_pred_labels):
    y_pred_bin = np.array([1 if p == "toxic" else 0 for p in y_pred_labels])
    y_true_bin = np.array(y_true_bin)

    acc = (y_true_bin == y_pred_bin).mean()
    tp = int(((y_true_bin == 1) & (y_pred_bin == 1)).sum())
    fp = int(((y_true_bin == 0) & (y_pred_bin == 1)).sum())
    fn = int(((y_true_bin == 1) & (y_pred_bin == 0)).sum())
    tn = int(((y_true_bin == 0) & (y_pred_bin == 0)).sum())

    precision = tp / (tp + fp) if (tp + fp) else 0.0
    recall    = tp / (tp + fn) if (tp + fn) else 0.0
    f1        = (2*precision*recall)/(precision+recall) if (precision+recall) else 0.0

    return {
        "accuracy": round(float(acc), 4),
        "precision": round(float(precision), 4),
        "recall": round(float(recall), 4),
        "f1": round(float(f1), 4),
        "tp": tp, "fp": fp, "fn": fn, "tn": tn
    }

# Prédictions pour chaque méthode
print("\n Prédictions…")
pred_zero = predict_zero_shot(texts)
pred_few  = predict_few_shot(texts)
pred_role = predict_role_prompting(texts)

# Évaluation
print("\n Évaluation :")
metrics = {}
metrics["zero_shot"]    = compute_metrics(y_true, pred_zero)
metrics["few_shot"]     = compute_metrics(y_true, pred_few)
metrics["role_prompt"]  = compute_metrics(y_true, pred_role)

for k, v in metrics.items():
    print(f"{k:>12} -> acc={v['accuracy']:.4f}  prec={v['precision']:.4f}  rec={v['recall']:.4f}  f1={v['f1']:.4f}  (tp={v['tp']}, fp={v['fp']}, fn={v['fn']}, tn={v['tn']})")

# Sauvegarde détaillée
out = df.copy()
out["pred_zero"]       = pred_zero
out["pred_few"]        = pred_few
out["pred_role"]       = pred_role
out.to_csv("predictions_finetuned_all_methods.csv", index=False)
print("\nSauvegardé: predictions_finetuned_all_methods.csv")

# Récapitulatif trié par F1
rank = (
    pd.DataFrame(metrics)
      .T.reset_index()
      .rename(columns={"index":"method"})
      .sort_values("f1", ascending=False)
)
print("\n Classement (par F1):")
print(rank.to_string(index=False))

"""# Part 5: Evaluation"""

##### MÉTRIQUES PAR CLASSE (Non-toxic / Toxic) + MACRO-F1
import numpy as np
import pandas as pd
from sklearn.metrics import precision_recall_fscore_support, f1_score

y_true = df["toxic"].astype(int).values

# 2) Utilitaires
def to_binary(preds_text):
    """Map 'toxic'/'non-toxic' -> 1/0 (fallback 'non-toxic' si autre)."""
    return np.array([1 if (str(p).strip().lower() == "toxic") else 0 for p in preds_text], dtype=int)

def align_len(y_true_bin, preds_dict):
    """Alerte et tronque si tailles différentes."""
    n = len(y_true_bin)
    aligned = {}
    for name, preds in preds_dict.items():
        if len(preds) != n:
            print(f"[WARN] {name}: {len(preds)} prédictions vs {n} vérités. Tronquage à {n}.")
            aligned[name] = preds[:n]
        else:
            aligned[name] = preds
    return aligned

def per_class_metrics(y_true_bin, y_pred_bin, model_name: str):
    """
    Retourne dict avec:
      Non-toxic P/R/F1 (classe 0), Toxic P/R/F1 (classe 1), Macro-F1
    """
    # Ordre des labels fixé: 0 (non-toxic), 1 (toxic)
    p, r, f1, support = precision_recall_fscore_support(
        y_true_bin, y_pred_bin, labels=[0, 1], zero_division=0
    )
    macro = f1_score(y_true_bin, y_pred_bin, average="macro")

    return {
        "Model": model_name,
        "Non-toxic P": round(float(p[0]), 4),
        "Non-toxic R": round(float(r[0]), 4),
        "Non-toxic F1": round(float(f1[0]), 4),
        "Toxic P": round(float(p[1]), 4),
        "Toxic R": round(float(r[1]), 4),
        "Toxic F1": round(float(f1[1]), 4),
        "Macro-F1": round(float(macro), 4),
    }

# 3) Aligner longueurs
preds_text = align_len(
    y_true,
    {
        "Zero-shot": pred_zero,
        "Few-shot": pred_few,
        "Role prompting": pred_role,
    }
)

# 4) Convertir en binaire
preds_bin = {name: to_binary(preds_text[name]) for name in preds_text}

# 5) Calcul et tableau final
rows = []
rows.append(per_class_metrics(y_true, preds_bin["Zero-shot"], "Zero-shot"))
rows.append(per_class_metrics(y_true, preds_bin["Few-shot"], "Few-shot"))
rows.append(per_class_metrics(y_true, preds_bin["Role prompting"], "Role prompting"))

metrics_table = pd.DataFrame(rows, columns=[
    "Model",
    "Non-toxic P", "Non-toxic R", "Non-toxic F1",
    "Toxic P", "Toxic R", "Toxic F1",
    "Macro-F1",
])

print("\nMétriques par classe :")
print(metrics_table.to_string(index=False))

# 6) Sauvegarde
metrics_table.to_csv("per_class_metrics.csv", index=False)
print("\nSauvegardé : per_class_metrics.csv")

##### Récap & ROC des modèles
import numpy as np, pandas as pd, matplotlib.pyplot as plt
from sklearn.metrics import (
    classification_report, precision_recall_fscore_support, f1_score,
    roc_auc_score, average_precision_score, roc_curve
)

def _exists(name:str)->bool: return name in globals()

models_payload=[]

# 1) Baseline TF-IDF (1–2g) + LinearSVC (pipeline)
if _exists("y_test") and _exists("y_pred") and _exists("y_score"):
    models_payload.append({"name":"Baseline: TF-IDF (1–2g) + LinearSVC",
                           "y_true":y_test,"y_pred":y_pred,"y_score":y_score})

# 2) MiniLM + Logistic Regression
if _exists("y_test") and _exists("y_pred_lr") and _exists("y_proba_lr"):
    models_payload.append({"name":"MiniLM + Logistic Regression",
                           "y_true":y_test,"y_pred":y_pred_lr,"y_score":y_proba_lr})

# 3) MiniLM + LinearSVC
if _exists("y_test") and _exists("y_pred_svm") and _exists("scores_svm"):
    models_payload.append({"name":"MiniLM + LinearSVC",
                           "y_true":y_test,"y_pred":y_pred_svm,"y_score":scores_svm})

# 4) RoBERTa (transformer)
if _exists("labels") and _exists("y_hat") and _exists("probs"):
    models_payload.append({"name":"RoBERTa-base (weighted)",
                           "y_true":labels,"y_pred":y_hat,"y_score":probs})
# 5) FT Seq2Seq (modèle fine-tuned)
if _exists("y_true") and _exists("yhat_zero") and _exists("probs_zero"):
    models_payload.append({"name":"FT Seq2Seq — Zero-shot prompt",
                           "y_true":y_true,"y_pred":[1 if z=="toxic" else 0 for z in yhat_zero],
                           "y_score":probs_zero})

if _exists("y_true") and _exists("yhat_few") and _exists("probs_few"):
    models_payload.append({"name":"FT Seq2Seq — Few-shot prompt",
                           "y_true":y_true,"y_pred":[1 if z=="toxic" else 0 for z in yhat_few],
                           "y_score":probs_few})

if _exists("y_true") and _exists("yhat_role") and _exists("probs_role"):
    models_payload.append({"name":"FT Seq2Seq — Role prompting",
                           "y_true":y_true,"y_pred":[1 if z=="toxic" else 0 for z in yhat_role],
                           "y_score":probs_role})

if not models_payload:
    raise RuntimeError("Aucun des jeux de variables attendus n’a été trouvé. "
                       "Ré-exécute d’abord les cellules d’entraînement.")

# Tableau récapitulatif
rows, text_reports = [], {}
for mp in models_payload:
    y_true, y_pred, y_score, name = mp["y_true"], mp["y_pred"], mp["y_score"], mp["name"]

    text_reports[name] = classification_report(
        y_true, y_pred, target_names=["non-toxic","toxic"], digits=3
    )

    p,r,f1_each,_ = precision_recall_fscore_support(y_true, y_pred, average=None, labels=[0,1])
    macro_f1 = f1_score(y_true, y_pred, average="macro")
    roc_auc  = roc_auc_score(y_true, y_score)
    pr_auc   = average_precision_score(y_true, y_score)

    rows.append({
        "Model": name,
        "Non-toxic P": round(p[0],3), "Non-toxic R": round(r[0],3), "Non-toxic F1": round(f1_each[0],3),
        "Toxic P": round(p[1],3),     "Toxic R": round(r[1],3),     "Toxic F1": round(f1_each[1],3),
        "Macro-F1": round(macro_f1,3),
        "ROC-AUC": round(roc_auc,4),
        "PR-AUC (toxic)": round(pr_auc,4),
    })

summary_df = pd.DataFrame(rows).sort_values("ROC-AUC", ascending=False).reset_index(drop=True)

# Affichage robuste
try:
    from IPython.display import display
    display(summary_df)
except Exception:
    print("\n=== Récapitulatif modèles ===")
    print(summary_df.to_string(index=False))

# Courbes ROC (une figure, toutes les courbes)
plt.figure(figsize=(7.5,6.5))
for mp in models_payload:
    fpr,tpr,_ = roc_curve(mp["y_true"], mp["y_score"])
    auc_val = roc_auc_score(mp["y_true"], mp["y_score"])
    plt.plot(fpr, tpr, label=f"{mp['name']} (AUC={auc_val:.3f})")

plt.plot([0,1],[0,1],"--",linewidth=1)
plt.title("ROC curves — Toxic vs. Non-toxic (test)")
plt.xlabel("False Positive Rate"); plt.ylabel("True Positive Rate")
plt.legend(loc="lower right"); plt.tight_layout()
plt.show()

# Imprimer les rapports texte complets pour l'annexe/log
for name, rep in text_reports.items():
    print("\n"+"="*80); print(name); print("="*80); print(rep)

